name: test

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: |
        npm install
        npm run build